server:
   port: 8082

spring:
  application:
    name: resource-server

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/bootlabs
          jwk-set-uri: http://localhost:8080/realms/bootlabs/protocol/openid-connect/certs


logging:
  level:
    org:
      springframework:
        security: DEBUG